name: shopify
description: "An E-commerce mobile app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_gen: any

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/colors.json

  fonts:
    - family: Suwannaphum
      fonts:
        - asset: assets/Suwannaphum-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"
flutter_intl:
  enabled: true